#!/usr/bin/python

import sys

from PySide import QtGui
from PySide import QtDeclarative
import os

def main():

    app = QtGui.QApplication(sys.argv)
    view = QtDeclarative.QDeclarativeView()

    if os.path.exists('/usr/share/n9client/qml'):
        view.setSource('/usr/share/n9client/qml/main.qml')
    else:
        view.setSource(os.path.join('qml','main.qml'))

    view.showFullScreen()
    app.exec_()

if __name__ == "__main__":
    main()
